# Generated by Django 6.0.3 on 2026-03-16 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='measure',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Measure', 'verbose_name_plural': 'Measures'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(help_text='MAC Address of the ESP32 (e.g., 00:1A:2B:3C:4D:5E)', max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='M5StickC Detector', help_text='Human-readable name for the device', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(help_text='The owner of the device', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='measure',
            name='base_bpm',
            field=models.FloatField(help_text='Baseline resting BPM used for calculation'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='bpm',
            field=models.FloatField(help_text='Current Beats Per Minute recorded by the device'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='device_mac',
            field=models.CharField(help_text='Logged MAC address at the time of measurement', max_length=17),
        ),
        migrations.AlterField(
            model_name='measure',
            name='is_lie',
            field=models.BooleanField(default=False, help_text='True if current BPM exceeds baseline by the threshold (e.g., > 20%)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='calibration_base_bpm',
            field=models.FloatField(blank=True, help_text='The calibrated resting heart rate at the start', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='device',
            field=models.ForeignKey(help_text='Device used during this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='api.device'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this session is currently ongoing'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(help_text='The user conducting the session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='device',
            table='api_device',
        ),
        migrations.AlterModelTable(
            name='measure',
            table='api_measure',
        ),
        migrations.AlterModelTable(
            name='session',
            table='api_session',
        ),
    ]
