# Generated by Django 6.0.3 on 2026-03-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_device_options_alter_measure_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='shake_intensity',
            field=models.FloatField(default=0.0, help_text='Vibration intensity measured by accelerometer'),
        ),
    ]
