# Generated by Django 6.0.3 on 2026-03-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_measure_shake_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='is_tremor_alert',
            field=models.BooleanField(default=False, help_text='True if vibrations exceed a threshold (e.g., > 0.5)'),
        ),
    ]
